# Generated by Django 6.0.3 on 2026-03-26 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_alter_member_options_remove_member_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='member_type',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('faculty', 'Faculty'), ('staff', 'Staff'), ('external', 'External')], default='student', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
