# Generated by Django 6.0.3 on 2026-04-02 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_member_department_member_email_member_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, unique=True)),
                ('fingerprint_hash', models.CharField(help_text='SHA-256 hash of browser fingerprint', max_length=64, unique=True)),
                ('session_key', models.CharField(max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['user_id'], name='models_anon_user_id_310952_idx'), models.Index(fields=['is_active', 'last_activity'], name='models_anon_is_acti_efdf09_idx')],
            },
        ),
        migrations.CreateModel(
            name='OverdueBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identifier', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('book_title', models.CharField(max_length=255)),
                ('book_author', models.CharField(blank=True, max_length=255)),
                ('resource_id', models.CharField(max_length=50)),
                ('checkout_date', models.DateField()),
                ('due_date', models.DateField()),
                ('days_overdue', models.IntegerField(default=0)),
                ('original_transaction', models.CharField(blank=True, max_length=255, null=True)),
                ('is_recovered', models.BooleanField(default=False)),
                ('recovery_date', models.DateTimeField(blank=True, null=True)),
                ('fine_imposed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-days_overdue'],
                'indexes': [models.Index(fields=['is_recovered'], name='models_over_is_reco_8fa9b5_idx'), models.Index(fields=['-days_overdue'], name='models_over_days_ov_d01770_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserAuthentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_library_id', models.CharField(blank=True, max_length=1024, null=True, unique=True)),
                ('encrypted_auth_data', models.CharField(blank=True, max_length=1024, null=True, unique=True)),
                ('auth_method', models.CharField(choices=[('library_id', 'Library ID'), ('student_id', 'Student ID'), ('credentials', 'Name + Phone + Credentials')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_banned', models.BooleanField(default=False)),
                ('ban_reason', models.TextField(blank=True)),
                ('ban_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_auth', to='models.member')),
            ],
        ),
        migrations.CreateModel(
            name='UserBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('inappropriate_content', 'Inappropriate Content Upload'), ('multiple_violations', 'Multiple Policy Violations'), ('overdue_books', 'Overdue Books Not Returned'), ('harassment', 'Harassment/Abuse'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('banned_by', models.CharField(blank=True, max_length=255)),
                ('is_permanent', models.BooleanField(default=False)),
                ('ban_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_auth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ban', to='models.userauthentication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('epub', 'EPUB')], max_length=10)),
                ('file', models.FileField(upload_to='user_books/%Y/%m/%d/')),
                ('file_size', models.BigIntegerField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='user_books/covers/')),
                ('pages_count', models.IntegerField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Admin verification status')),
                ('is_banned', models.BooleanField(default=False, help_text='Banned by admin')),
                ('ban_reason', models.TextField(blank=True)),
                ('download_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('review_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_books', to='models.anonymoususer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('is_flagged', models.BooleanField(default=False, help_text='Admin flagged for inappropriate content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='models.userbook')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.anonymoususer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('days_overdue', models.IntegerField()),
                ('reason', models.TextField(blank=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='models.member')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.resource')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fine', to='models.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_paid'], name='models_fine_is_paid_e2a389_idx'), models.Index(fields=['member'], name='models_fine_member__ab5b48_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='userauthentication',
            index=models.Index(fields=['is_active'], name='models_user_is_acti_3a17d7_idx'),
        ),
        migrations.AddIndex(
            model_name='userauthentication',
            index=models.Index(fields=['is_banned'], name='models_user_is_bann_8ac2ad_idx'),
        ),
        migrations.AddIndex(
            model_name='userbook',
            index=models.Index(fields=['is_banned'], name='models_user_is_bann_816679_idx'),
        ),
        migrations.AddIndex(
            model_name='userbook',
            index=models.Index(fields=['rating_avg'], name='models_user_rating__73dc6b_idx'),
        ),
        migrations.AddIndex(
            model_name='userbook',
            index=models.Index(fields=['-created_at'], name='models_user_created_c285a7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userreview',
            unique_together={('book', 'user')},
        ),
    ]
