# Generated by Django 6.0.3 on 2026-04-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_anonymoususer_overduebook_userauthentication_userban_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauthentication',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
