# Generated by Django 6.0.3 on 2026-04-02 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_userauthentication_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_books', to='models.category'),
        ),
        migrations.AddField(
            model_name='userbook',
            name='publication_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userbook',
            name='publisher',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userbook',
            name='resource_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userbook',
            name='shelf_location',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
